version = 1

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "cxx"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",
    "angular"
  ]
  environment = [
    "nodejs",
    "mongo",
    "jquery"
  ]

[[transformers]]
name = "google-java-format"

[[transformers]]
name = "black"

[[transformers]]
name = "ruff"

[[transformers]]
name = "clang-format"

[[transformers]]
name = "standardjs"

[[transformers]]
name = "prettier"